spring.application.name: gift-cards-api
server:
  port: 8080
spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true
  error:
    include-stack-trace: DEBUG
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:gift_cards;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      initialize: true
    jpa:
      properties:
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true
      hibernate:
        ddl-auto: create
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
      host: smtp.gmail.com
      username: ENC(64jiip4nDgmWVOd1D+kRKLrGyGK/Xt1S2LnhSRR5W4OO+6oUqt/9bdE9zoKLAV9jMnHy4pSG0Th7kariuo3JfQ==)
      password: ENC(rrRnpPwAKuSX9pu3Ggb3A8482I5DJsbK40iDzaPRi2jV4YHcKqwv+7bVMwXgTEQjUFZjaJGAVRgxlbF85U0J1g==)
      port: 587
jasypt:
  encryptor:
    password: secret
logging:
  level:
    org:
      springframework:
        security: DEBUG
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
