spring.application.name: gift-cards-api
server:
  port: 9000
spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true
  error:
    include-stack-trace: DEBUG
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:giftcards
      username: sa
      password:
      initialize: true
    jpa:
      properties:
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true
      hibernate:
        ddl-auto: create-drop

